name: iOS PR Checks (Light)

on:
  pull_request:
    branches:
      - Development

jobs:
  pr-checks:
    name: Lint & Test
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Run SwiftLint
        run: |
          brew install swiftlint || true
          swiftlint lint --strict
        continue-on-error: true

      - name: Build & Test
        run: |
          xcodebuild \
            -workspace ios/YourApp.xcworkspace \
            -scheme YourAppScheme \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            clean test | xcpretty
